#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/gitlab
- name: Populate service facts
  ansible.builtin.service_facts: {}

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Setup Gitlab
  ansible.builtin.include_tasks: setup.yml