---

# Create Apps Directory
- name: Create apps directory
  ansible.builtin.file:
    path: "{{ app_dir }}/{{ item }}"
    state: directory
    mode: '0755'
    owner: root
  loop:
    - docker
    - registry
    - nginx

# Create 