---

- name: Create registry domain
  ansible.builtin.file:
    path: /etc/docker/certs.d/{{ domain }}
    state: directory
    mode: '0755'
    owner: root

- name: Copy cert to registry domain
  ansible.builtin.copy:
    src: "superasian.net.cert"
    dest: "/etc/docker/certs.d/{{ domain }}/superasian.net.cert"
    mode: 0644

- name: Copy key to registry domain
  ansible.builtin.copy:
    src: "superasian.net.key"
    dest: "/etc/docker/certs.d/{{ domain }}/superasian.net.key"
    mode: 0600

# Add daemon config
- name: Copy daemon.json
  ansible.builtin.template:
    src: "daemon.json.j2"
    dest: "/etc/docker/daemon.json"
  notify: Restart docker
