---

# Perform full system upgrade as needed
- name: Perform system updates (example)
  ansible.builtin.apt:
    update_cache: yes
    upgrade: dist
  register: apt_update_result

- name: Check for reboot-required file
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Notify handler if reboot is required
  ansible.builtin.debug:
    msg: "Reboot is required for {{ hostname }}"
  when: reboot_required_file.stat.exists
  notify: Reboot host

# Install omvextra & compose
- name: Install omvextra & compose
  ansible.builtin.shell:
    cmd: |
      apt update && apt install -y wget curl git htop bmon lm-sensors strace
      wget -O - https://github.com/OpenMediaVault-Plugin-Developers/packages/raw/master/install | bash
      apt update && apt install -y openmediavault-compose

# Add daemon config
- name: Copy daemon.json
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: /etc/docker/{{ item }}
  notify: Restart docker
  loop:
    - daemon.json

# Create Apps Directory
- name: Create apps directory
  ansible.builtin.file:
    path: "{{ app_dir }}/{{ item }}"
    state: directory
    mode: '0755'
    owner: "{{ app_user }}"
    recurse: yes
  loop:
    - docker-registry-ui
    - nginx
    - registry
