---

# Fully upgrade the nodes
- name: Fully upgrade the node
  ansible.builtin.shell:
    cmd: |
      apt update && apt dist-upgrade -y
  register: omv_upgrade

# Reboot the server
- name: Reboot the machine
  ansible.builtin.reboot:
    reboot_timeout: 300
  when:
    - omv_upgrade == changed

# Install omvextra & compose
- name: Fully upgrade the node
  ansible.builtin.shell:
    cmd: |
      wget -O - https://github.com/OpenMediaVault-Plugin-Developers/packages/raw/master/install | bash
      apt update && apt install -y openmediavault-compose

# Disable Firewalld
- name: Disable FIREWALLD
  ansible.builtin.systemd:
    name: firewalld
    state: stopped
    enabled: false
  when:
    - ansible_facts.services["firewalld.service"] is defined
    - ansible_facts.services["firewalld.service"].status != "not-found"
  notify: "Restart {{ service_name }}"

# 