#!/bin/bash

# Method 1 (Kubernetes)
# Setup Kubernetes auth
vault auth enable kubernetes

# Configure Kubernetes auth
vault write auth/kubernetes/config \
  token_reviewer_jwt="$(kubectl get secret vault-auth -o go-template='{{ .data.token }}' | base64 --decode)" \
  kubernetes_host="$(kubectl config view --raw --minify --flatten --output='jsonpath={.clusters[0].cluster.server}')" \
  kubernetes_ca_cert="$(kubectl config view --raw --minify --flatten --output='jsonpath={.clusters[0].cluster.certificate-authority-data}' | base64 --decode)" \
  disable_local_ca_jwt=true

vault write auth/kubernetes/role/external-secrets \
  bound_service_account_names=eso-sa \
  bound_service_account_namespaces=external-secrets-system \
  policies=external-secrets \
  ttl=1h

# Testing vault auth with eso-sa token
TOKEN_REVIEW_SJWT=$(kubectl get secret eso-sa -n external-secrets-system -o go-template='{{ .data.token }}' | base64 --decode)
curl \
  --request POST \
  --data '{"jwt": "'$TOKEN_REVIEW_SJWT'", "role": "external-secrets"}' \
  https://vault.superasian.net/v1/auth/kubernetes/login

# Method 2 (AppRole)
# Setup AppRole auth
vault auth enable approle

# # Create AppRole
vault write auth/approle/role/external-secrets \
  secret_id_ttl=0 \
  token_ttl=20m \
  token_max_ttl=30m \
  policies=external-secrets

# Get role ID
ROLE_ID=$(vault read auth/approle/role/external-secrets/role-id | awk 'NR==3 { print $2 }')

# Generate secret ID
SECRET_ID=$(vault write -f auth/approle/role/external-secrets/secret-id | awk 'NR==3 { print $2 }')

kubectl create secret generic external-secrets \
  --namespace external-secrets-system \
  --from-literal=role-id=$ROLE_ID \
  --from-literal=secret-id=$SECRET_ID

exit 0;