#!/bin/bash
secrets=("kv" "kubernetes" "ldap" "pki" "ssh" "totp" "transit" "aws" "azure" "gcp" "database")
    for secret in ${secrets[@]}; do
        vault secrets enable -path=$secret $secret
    done
exit 0;