#!/bin/bash
secrets=("kv" "kubernetes" "ldap" "pki" "ssh" "totp" "transit" "alicloud" "aws" "azure" "gcp" "gcpkms" "consul" "database" "nomad" "rabbitmq")
    for secret in ${secrets[@]}; do
        vault secrets enable -path=$secret $secret
    done
exit 0;