---
# Setup Goldfish
services:
  goldfish:
    # Using the image provided by a community maintainer
    image: mvisonneau/goldfish:latest
    container_name: goldfish
    user: "1000"
    ports:
      # Map container port 8443 to host port 443
      - "8443:443"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    environment:
      # REQUIRED: The address of your running Vault server
      - VAULT_ADDR=https://vault.superasian.net
      - VAULT_SKIP_VERIFY=true
    cap_add:
    - IPC_LOCK
    volumes:
      - /srv/AppData/vault/config/goldfish.hcl:/etc/goldfish/goldfish.hcl:ro
      - /srv/AppData/vault/ssl/cert.pem:/etc/ssl/goldfish.crt:ro
      - /srv/AppData/vault/ssl/key.pem:/etc/ssl/goldfish.key:ro
    restart: unless-stopped
    network_mode: bridge
    entrypoint: goldfish -config=/etc/goldfish/goldfish.hcl