#!/bin/bash
vault auth enable approle

vault policy write goldfish config/goldfish.hcl

vault write auth/approle/role/goldfish role_name=goldfish policies=admin,goldfish secret_id_num_uses=1 secret_id_ttl=5m period=24h token_ttl=0 token_max_ttl=0

vault write auth/approle/role/goldfish/role-id role_id=goldfish

# production goldfish needs a generic secret endpoint. See Configuration page for details
vault kv put kv/goldfish DefaultSecretPath="kv/" UserTransitKey="usertransit" BulletinPath="kv/bulletins/"