#!/bin/bash
vault auth enable approle

vault policy write goldfish - <<EOF
# [mandatory]
# store goldfish run-time settings here
# goldfish hot-reloads from this endpoint every minute
# List, create, update, and delete kv secrets
path "kv/*" {
  capabilities = ["create", "read", "update", "delete", "list", "sudo"]
}


# [optional]
# to enable transit encryption, see wiki for details
path "transit/encrypt/goldfish" {
  capabilities = ["read", "update"]
}
path "transit/decrypt/goldfish" {
  capabilities = ["read", "update"]
}


# [optional]
# for goldfish to fetch certificates from PKI backend
path "pki/issue/goldfish" {
  capabilities = ["update"]
}
EOF

vault write auth/approle/role/goldfish role_name=goldfish policies=admin,goldfish secret_id_num_uses=1 secret_id_ttl=5m period=24h token_ttl=0 token_max_ttl=0

vault write auth/approle/role/goldfish/role-id role_id=goldfish

# production goldfish needs a generic secret endpoint. See Configuration page for details
vault kv put kv/goldfish DefaultSecretPath="kv/" UserTransitKey="usertransit" BulletinPath="kv/bulletins/"