---
app_dir: "/srv/AppData"
app_user: "k0ng"
artifactory_user: "1030"
artifactory_group: "1030"
nginx_dir: "{{ app_dir }}/nginx"
version: "7.125.11"
product: "artifactory-oss"
srv_ip: "10.0.0.25"
repo_url: "https://www.superasian.net/repo"
# defaults file for artifactory

# The location where Artifactory should store data.
artifactory_file_store_dir: /srv/dev-disk-by-uuid-ff1b1617-0bd4-45a8-8a10-e859b8de7f80/ARCHIVE

# The type of installation of artifactory.
# Choose from "oss", "jcr" or "cpp-ce".
artifactory_flavour: oss

