[masters]
infra01  ansible_host=10.0.0.21 ansible_connection=ssh
infra02  ansible_host=10.0.0.22 ansible_connection=ssh
infra03  ansible_host=10.0.0.23 ansible_connection=ssh

[workers]
w0rk3r2  ansible_host=10.0.0.26 ansible_connection=ssh

[rke2_cluster:vars]
sshd_use_pam=no
sshd_password_authentication=no
sshd_challenge_response_authentication=no
sshd_permitroot_login=no

[rke2_cluster:children]
masters
workers
