#SPDX-License-Identifier: MIT-0
---
# handlers file for roles/ipa
- name: Restart systemd-sysctl
  ansible.builtin.service:
    state: restarted
    name: systemd-sysctl

- name: Restart firewalld
  ansible.builtin.service:
    state: restarted
    name: firewalld

- name: Restart ipa
  ansible.builtin.service:
    state: restarted
    name: ipa

- name: Reboot host
  ansible.builtin.reboot:
    reboot_timeout: 300