#SPDX-License-Identifier: MIT-0
---
app_dir: "/srv/AppData"
app_user: "k0ng"
nginx_dir: "{{ app_dir }}/nginx"
mon_dir: "{{ app_dir }}/monitoring"
alertmanager_dir: "{{ mon_dir }}/alertmanager"
grafana_dir: "{{ mon_dir }}/grafana"
influxdb_dir: "{{ mon_dir }}/influxdb"
loki_dir: "{{ mon_dir }}/loki"
prometheus_dir: "{{ mon_dir }}/prometheus"
promtail_dir: "{{ mon_dir }}/promtail"
telegraf_dir: "{{ mon_dir }}/telegraf"
tempo_dir: "{{ mon_dir }}/tempo"
repo_url: "https://www.superasian.net/repo"
srv_ip: "10.0.0.16"
