---
# Create AppData Directory
- name: Create apps directory
  ansible.builtin.file:
    path: "{{ app_dir }}/{{ item }}"
    state: directory
    mode: '0755'
    owner: "{{ app_user }}"
    recurse: yes
  loop:
    - artifactory
    - nginx
    - uptime-kuma
    - tig
