---
# Create Artifactory Directory
- name: Create artifactory directory
  ansible.builtin.file:
    path: "{{ app_dir }}/artifactory"
    state: directory
    mode: 0755
    owner: "{{ artifactory_user }}"
    group: "{{ artifactory_group }}"

- name: Copy and extract tar file
  ansible.builtin.unarchive:
    src: "files/{{ jfrog_product }}-{{ artifactory_version }}-compose.tar.gz"  # Path to the archive on the Ansible control machine
    dest: "{{ app_dir}}/"   # Absolute path on the remote host where the archive will be extracted
    remote_src: no                     # Set to 'yes' if the archive is already on the remote host
    owner: "app_user"                      # (Optional) User to own the extracted files                    # (Optional) Group to own the extracted files
    mode: '0755'                       # (Optional) Permissions for the extracted files
    extra_opts: ['--strip-components=1'] # (Optional) Pass extra options to the unarchive command (e.g., to strip directories)

# Copy environment file
- name: Copy environment file
  ansible.builtin.template:
    src: "templates/artifactory-env.j2"
    dest: "{{ app_dir }}/{{ jfrog_product }}-{{ artifactory_version }}/.env"
    mode: 0755
    owner: "{{ app_user }}"
