---
# Setup hostname and /etc/hosts for FreeIPA server
# - name: Deploy /etc/hosts from template
#   ansible.builtin.template:
#     src: hosts.j2
#     dest: /etc/hosts
#     owner: root
#     group: root
#     mode: '0644'
#     backup: true
#   notify: Restart systemd-sysctl

# Clone the Mailcow repository
- name: Clone the Mailcow repository
  ansible.builtin.git:
    repo: 'https://github.com/mailcow/mailcow-dockerized.git'
    dest: "{{ mailcow_dir }}"
    version: master
    force: true
    update: true

# Copy mailcow config & compose files
- name: Copy config & compose files
  ansible.builtin.template :
    src: "{{ item }}.j2"
    dest: "{{ mailcow_dir }}/{{ item }}"
    owner: root
    group: root
    mode: '0644'
    follow: yes
    force: yes
  loop:
    - mailcow.conf
    - docker-compose.yml

# Start the Mailcow server using docker-compose
- name: Start Mailcow server
  ansible.builtin.shell:
    cmd: |
      docker compose up -d
    chdir: "{{ mailcow_dir }}"
  register: mailcow_start_result
  until: mailcow_start_result.rc == 0
  retries: 3
  delay: 30

# Display the result of starting the Mailcow server
- name: Display Mailcow start result
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop: "{{ mailcow_start_result.stdout_lines }}"
  when: mailcow_start_result.stdout_lines is defined
