---
# vars file for artifactory
artifactory_home: /etc/opt/jfrog/artifactory
artifactory_logs: /opt/jfrog/artifactory/var/log
artifactory_file_store_dir: "{{ app_dir }}/artifactory"
artifactory_package: jfrog-artifactory-{{ artifactory_flavour }}

# vars for docker compose
DOCKER_REGISTRY: "releases-docker.jfrog.io"
ARTIFACTORY_VERSION: 7.125.11
ROOT_DATA_DIR: "/srv/AppData/artifactory"
JF_ROUTER_ENTRYPOINTS_EXTERNALPORT: 8082
JF_ROUTER_ENTRYPOINTS_INTERNALPORT: {}
JF_SHARED_NODE_IP: 10.0.0.25
JF_SHARED_NODE_ID: artifactory-oss
JF_SHARED_NODE_NAME: artifactory-oss