---
# Setup Portainer
services:
  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer
    user: "1026"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /volume1/apps/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    network_mode: bridge