#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/ipa
- name: Populate service facts
  ansible.builtin.service_facts: {}

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Setup FreeIPA Server on RHEL 9 or Rocky 9
  ansible.builtin.include_tasks: setup.yml
