---
name: mariadb
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    user: "1000"
    secrets:
      - mysql_root_password
      - mysql_app_password
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MARIADB_PASSWORD_FILE: /run/secrets/mysql_app_password
      MARIADB_DATABASE: goldfish
      MARIADB_USER: apps_user
    ports:
      - "3306:3306"
    volumes:
      - /srv/AppData/mariadb/config/50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf:ro
      - /srv/AppData/mariadb/data:/var/lib/mysql
    networks:
      - backend

  backup:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mariadb-backup
    restart: always
    tty: true
    networks:
      - backend
    volumes:
    - /srv/AppData/mariadb/backup:/backup/mysql
    environment:
    - MYSQL_HOST=mariadb
    secrets:
      - mysql_root_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
    ports:
      - "8090:80"
    networks:
      - backend
    depends_on:
      - mariadb
# secret files on server
secrets:
  mysql_root_password:
    file: /srv/AppData/mariadb/secrets/db.txt
  mysql_app_password:
    file: /srv/AppData/mariadb/secrets/app.txt
networks:
  backend:
    driver: bridge