---
- name: Populate service facts
  ansible.builtin.service_facts: {}

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

# Create mariadb dirctories
- name: Create mariadb directories
  ansible.builtin.file:
    path: "{{ mariadb_dir }}/{{ item }}"
    state: directory
    mode: '0755'
    owner: "{{ app_user }}"
  loop:
    - backup
    - config
    - data
    - scripts
    - secrets

# Copy config files
- name: Copy config files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
    owner: root
  loop:
    - { src: 'files/backup-mysql.sh', dest: '{{ mariadb_dir }}/scripts/backup-mysql.sh' }
    - { src: 'files/Dockerfile', dest: '{{ mariadb_dir }}/Dockerfile' }
    - { src: '50-server.cnf', dest: '{{ mariadb_dir}}/config/50-server.cnf'}

# Create secrets
- name: Create secrets
  ansible.builtin.shell: |
      openssl rand -base64 16 | tr -dc _A-Z-a-z-0-9 > {{ mariadb_dir }}/secrets/db.txt
      openssl rand -base64 16 | tr -dc _A-Z-a-z-0-9 > {{ mariadb_dir }}/secrets/app.txt
  register: secrets_value

# Copy db-staging nginx config
- name: Copy db-staging nginx config
  ansible.builtin.template:
    src: "templates/{{ item }}.j2"
    dest: "{{ nginx_dir }}/conf.d/{{ item }}"
    mode: 0644
    owner: root
  loop:
    - db-ui.conf
  notify: Restart nginx

# Start mariadb stack
- name: Start mariadb stack
  ansible.builtin.command:
    chdir: "{{ mariadb_dir }}"
    cmd: "docker compose -f mariadb.yml up -d"
  register: compose_result
  until: compose_result.rc == 0
  retries: 5
  delay: 10

# Display compose output
- name: Display compose result standard output lines
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop: "{{ compose_result.stdout_lines }}"
  when: compose_result.stdout_lines is defined
