---
name: nextcloud
services:
  nextcloud:
    user: "1000"
    image: nextcloud:apache
    container_name: nextcloud
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    restart: always
    ports:
      - 8080:80
    volumes:
      - /srv/AppData/nextcloud:/var/www/html
      - /srv/AppData/nextcloud/apps:/var/www/html/apps
      - /srv/AppData/nextcloud/secrets:/run/secrets
      - /srv/AppData/nextcloud/config:/var/www/html/config
      - /srv/AppData/nextcloud/data:/var/www/html/data
    environment:
      # Nextcloud configuration
      - APACHE_BODY_LIMIT=1GiB
      - NEXTCLOUD_DATA_DIR=/var/www/html/data
      - NEXTCLOUD_TRUSTED_DOMAINS={{ domain }}
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=/run/secrets/nextcloud_admin_password
      - PHP_MEMORY_LIMIT=512M
      - PHP_UPLOAD_LIMIT=512M
      # Database configuration
      - POSTGRES_HOST=10.0.0.252  # IP or DNS name of external DB
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=Letmein123
    secrets:
      - postgres_password
      - nextcloud_admin_password

secrets:
  nextcloud_admin_password:
    file: /srv/AppData/nextcloud/secrets/nextcloud_admin_password.txt # put admin password in this file
  postgres_password:
    file: /srv/AppData/nextcloud/secrets/postgres_password.txt # put postgresql password in this file
