app_dir: "/srv/dev-disk-by-uuid-b5f61a9b-1827-498b-a77b-7caf811c025b/DATA"
app_user: "k0ng"
domain: "harbor.superasian.net"
github_url: "https://github.com/goharbor/harbor/releases/download"
harbor_version: "v2.14.0"
harbor_dir: "{{ app_dir }}/harbor"