app_dir: "/srv/dev-disk-by-uuid-257808ca-8f49-439b-88a7-3971eda1121c/AppData"
app_user: "k0ng"
domain: "harbor.superasian.net"
github_url: "https://github.com/goharbor/harbor/releases/download"
harbor_version: "v2.14.0"
harbor_dir: "{{ app_dir }}/harbor"
nginx_dir: "{{ app_dir }}/nginx"