---
name: Telegraf + InfluxDB2 + Grafana
services:
  ## Influxdb2 Service
  influxdb2:
    image: influxdb:latest
    network_mode: bridge
    container_name: influxdb2
    ports:
      - "8086:8086"
    volumes:
      - type: bind
        source: /AppData/influxdb2/data
        target: /var/lib/influxdb2
      - type: bind
        source: /AppData/influxdb2/config
        target: /etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=k0ng
      - DOCKER_INFLUXDB_INIT_PASSWORD=0Penup!@#
      - DOCKER_INFLUXDB_INIT_ORG=PHAMCS
      - DOCKER_INFLUXDB_INIT_BUCKET=chooseBucketName
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=p9avK9R4234nWVeyC9YovQPL
    restart: always
  ## Telegraf Service
  telegraf:
    image: telegraf:latest
    network_mode: bridge
    pid: "host"
    container_name: telegraf
    user: "1000:100"
    depends_on:
      - influxdb2
    links:
      - influxdb2
    ports:
      - "8092:8092"
      - "8094:8094"
      - "8125:8125"
    volumes:
      - /AppData/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/host/sys:ro
      - /proc:/host/proc:ro
      - /etc:/host/etc:ro
    environment:
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
      - HOST_ETC=/host/etc
    restart: always
  ## Grafana Service
  grafana:
    image: grafana/grafana:latest
    network_mode: bridge
    container_name: grafana
    depends_on:
      - influxdb2
    links:
      - influxdb2
    user: "1000:100"
    environment:
      - GF_LOG_LEVEL=debug
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=superasian.net
      - GF_SERVER_ROOT_URL=https://tig.superasian.net
      - GF_SERVER_CERT_FILE=/etc/grafana/grafana.crt
      - GF_SERVER_KEY_FILE=/etc/grafana/grafana.key
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - /AppData/grafana/config:/etc/grafana
      - /AppData/grafana/data:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: always