---
# Setup Portainer Stack
services:
  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /srv/AppData/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    network_mode: bridge

  # Setup Node Exporter
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    network_mode: bridge
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($|/)'
    ports:
      - "9100:9100"
    restart: unless-stopped
