---
services:
  # Setup Node Exporter
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    # Use 'host' PID namespace to allow the exporter to see all host processes
    pid: host
    # Command line arguments for the node exporter
    command:
      - '--path.rootfs=/host'
    ports:
      # Expose the metrics port on the host
      - '9100:9100'
    volumes:
      # Mount the host root filesystem into the container at /host as read-only (ro)
      - '/:/host:ro'
    restart: unless-stopped
    network_mode: bridge