---
# Setup Common Stack
name: Portainer
services:
  # Setup Portainer
  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    network_mode: bridge
  # The Cloudflare Tunnel agent
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token eyJhIjoiOWEyNmQwY2I4NDM4OTRhODY1NmFjZDUwNmYyZWJlOWMiLCJ0IjoiMmMwNmNiYmYtMTI5Yi00YmQxLTg2MjktNTk0M2I3NzZmMDg1IiwicyI6Ik9HTmtOR0kxTXpNdE1tVTVaaTAwTnpFMUxXSXhNbUV0WVRnM01tVXlZek0zTkdGayJ9
    network_mode: bridge
volumes:
  portainer_data: