---
# Create Vault Directory
- name: Create vault directory
  ansible.builtin.file:
    path: "{{ vault_dir }}/{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ app_user }}"
  loop:
    - config
    - data
    - logs
    - plugins
    - scripts
    - ssl

# Copy vault config & cert
- name: Copy vault config and cert
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
    owner: "{{ app_user }}"
  loop:
    - { src: 'files/tls.cert', dest: '{{ vault_dir }}/ssl/tls.crt' }
    - { src: 'files/tls.key', dest: '{{ vault_dir }}/ssl/tls.key' }
    - { src: 'files/vault-stack.yml', dest: '{{ vault_dir }}/vault-stack.yml' }

# Copy vault scripts
- name: Copy vault config and cert
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
    owner: "{{ app_user }}"
  loop:
    - { src: 'files/enable_vault_secrets', dest: '{{ vault_dir }}/scripts/enable_vault_secrets' }
    - { src: 'files/eso_vault_k8s_auth', dest: '{{ vault_dir }}/scripts/eso_vault_k8s_auth' }
    - { src: 'files/vault_goldfish_prep', dest: '{{ vault_dir }}/scripts/vault_goldfish_prep' }

# Copy Vault & Goldfish config
- name: Copy Vault & Goldfish config
  ansible.builtin.template:
    src: "templates/{{ item }}.j2"
    dest: "{{ vault_dir }}/config/{{ item }}"
    mode: 0644
    owner: "{{ app_user }}"
  loop:
    - admin-policy.hcl
    - goldfish.hcl
    - vault.hcl

# Download binaries & plugins
- name: Download binaries & plugins
  ansible.builtin.shell: |
    curl -L {{ repo_url }}/vault_1.21.3_linux_amd64 -o /usr/local/bin/vault
    curl -L {{ repo_url }}/docker-credential-vault-login -o /usr/local/bin/docker-credential-vault-login
    chmod 0755 /usr/local/bin/*

# Start Vault
- name: Start Vault
  ansible.builtin.command:
    chdir: "{{ vault_dir }}"
    cmd: "docker compose -f vault-stack.yml up -d"
  register: compose_result
  until: compose_result.rc == 0
  retries: 5
  delay: 10

# Display compose output
- name: Display compose result standard output lines
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop: "{{ compose_result.stdout_lines }}"
  when: compose_result.stdout_lines is defined

# Copy Vault nginx config
- name: Copy vault nginx config
  ansible.builtin.template:
    src: "templates/{{ item }}.j2"
    dest: "{{ nginx_dir }}/conf.d/{{ item }}"
    mode: 0644
    owner: root
  loop:
    - vault.conf
  notify: Restart nginx
