---
# Setup Shares
- name: Setup Share AppData
  ansible.builtin.import_role:
    name: tafeen.syno_add_shares
  vars:
    syno_shares:
      - name: AppData
        description: Application Data
        path: /volume1/AppData
        recycle: false
        rights:
          RO:
            - guest
          RW: 
            - k0ng
  register: shares_setup
  until: shares_setup.rc == 0

# Display shares setup output
- name: Display shares setup result standard output lines
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop: "{{ shares_setup.stdout_lines }}"
  when: shares_setup.stdout_lines is defined