---
# Setup AppData Shares
- name: Setup Application Data Share
  ansible.builtin.import_role:
    name: tafeen.synology.syno_add_shares
  vars:
    syno_shares:
      - name: AppData
        description: Application Data
        path: /volume1/AppData
        recycle: false
        rights:
          RO:
            - guest
          RW:
            - k0ng
  register: appdata_setup
  until: appdata_setup.rc == 0

# Display AppData shares output
- name: Display AppData shares result standard output lines
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop: "{{ appdata_setup.stdout_lines }}"
  when: appdata_setup.stdout_lines is defined

# Setup Docker Shares
- name: Setup Docker Share
  ansible.builtin.import_role:
    name: tafeen.synology.syno_add_shares
  vars:
    syno_shares:
      - name: docker
        description: Docker Data
        path: /volume1/docker
        recycle: false
        rights:
          RO:
            - guest
          RW:
            - k0ng
  register: docker_setup
  until: docker_setup.rc == 0

# Display Docker shares output
- name: Display Docker shares result standard output lines
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop: "{{ docker_setup.stdout_lines }}"
  when: docker_setup.stdout_lines is defined
