---
# Install Golang for synology
- name: Copy and extract tar file
  ansible.builtin.unarchive:
    src: "https://go.dev/dl/go1.26.1.linux-amd64.tar.gz"  # Path to the archive on the Ansible control machine
    dest: /usr/local           # Absolute path on the remote host where the archive will be extracted
    remote_src: true                     # Set to 'yes' if the archive is already on the remote host
    owner: root            # (Optional) User to own the extracted files
    mode: '0755'                       # (Optional) Permissions for the extracted files
    #extra_opts: ['--strip-components=1'] # (Optional) Pass extra options to the unarchive command (e.g., to strip directories)

# Download binaries for synology
- name: Download binaries
  ansible.builtin.get_url:
    url: "{{ repo_url }}/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: '0755'
    owner: root
  loop:
    - vault
    - docker-credential-vault-login

# Create apps directory for synology
- name: Create apps directory
  ansible.builtin.file:
    path: "/volume1/apps/{{ item }}"
    state: directory
    owner: "{{ app_user }}"
    mode: '0755'
  loop:
    - portainer
    - quake3
    - uptime-kuma
    - ut99-server
    - vault

# Create vaultdirectory for synology
- name: Create vault directory
  ansible.builtin.file:
    path: "/volume1/apps/vault/{{ item }}"
    state: directory
    owner: "{{ app_user }}"
    mode: '0755'
  loop:
    - config
    - data
    - logs
    - plugins
    - ssl

# Copy Compose files for synology
- name: Copy compose files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0644'
    owner: "{{ app_user }}"
  loop:
    - { src: 'portainer.yml', dest: '/volume1/apps/portainer/docker-compose.yml' }
    - { src: 'quake3.yml', dest: '/volume1/apps/quake3/docker-compose.yml' }
    - { src: 'q3server.cfg', dest: '/volume1/apps/quake3/q3server.cfg' }
    - { src: 'maprotation.cfg', dest: '/volume1/apps/quake3/maprotation.cfg' }
    - { src: 'vault.yml', dest: '/volume1/apps/vault/docker-compose.yml' }
    - { src: 'vault.hcl', dest: '/volume1/apps/vault/config/vault.hcl' }
    - { src: 'uptime-kuma.yml', dest: '/volume1/apps/uptime-kuma/docker-compose.yml' }
    - { src: 'ut99-server.yml', dest: '/volume1/apps/ut99-server/docker-compose.yml' }
