---
# Install packages on Synology DSM
- name: Install packages
  ansible.builtin.import_role:
    name: tafeen.synology.syno_pkg_install
  vars:
    syno_upgrade_packages: true
    syno_packages:
        # Dependencies must install before application, otherwise installation will fail due to missing dependencies.
        # For example, Node.js_18 must be installed before SynologyPhotos, otherwise SynologyPhotos installation will fail due to missing Node.js_v18 dependency.
        - DhcpServer
        - DNSServer
        - Docker
        - FileStation
        - LogCenter
        - NoteStation
        - Perl
        - WebStation
        - SynologyApplicationService
        - Node.js_v18
        - SynologyPhotos
        - TextEditor
        
  register: pkg_install
  until: pkg_install.rc == 0

# Display install output
- name: Display install result standard output lines
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop: "{{ pkg_install.stdout_lines }}"
  when: pkg_install.stdout_lines is defined