---
# Install packages on Synology DSM
- name: Install packages
  ansible.builtin.import_role:
    name: tafeen.synology.syno_pkg_install
  vars:
    syno_upgrade_packages: true
    syno_packages:
        - Apache2.4
        - DhcpServer
        - DNSServer
        - Docker
        - FileStation
        - LogCenter
        - Node.js_v18
        - NoteStation
        - Perl
        - SynologyApplicationService
        - SynologyPhotos
        - TextEditor
  register: pkg_install
  until: pkg_install.rc == 0

# Display install output
- name: Display install result standard output lines
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop: "{{ pkg_install.stdout_lines }}"
  when: pkg_install.stdout_lines is defined