#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/synology
# Setup shares folder
- name: Setup Synology shares
  ansible.builtin.include_tasks: addshares.yml

# Install packages
- name: Install Synology packages
  ansible.builtin.include_tasks: installpkg.yml

# Setup PXE Server
- name: Setup PXE Server
  ansible.builtin.include_tasks: pxe.yml

# Setup Python venv and install requirements
- name: Setup Python venv and install requirements
  ansible.builtin.include_tasks: pyvenv-setup.yml

# Setup Tools
- name: Setup Tools
  ansible.builtin.include_tasks: tools.yml
