---
# Setup Python for synology. Make sure python3.9 installed from Package Center before run playbook
- name: Create a new user with specific attributes
  ansible.builtin.user:
    name: "{{ syno_user }}"
    uid: 1026
    state: present
    shell: /bin/bash
    generate_ssh_key: true
    create_home: false
    home: "{{ home_dir }}"
    groups: users,http,administrators
    append: true  # Keeps existing groups; prevents overwriting

# Create el_tracker venv and install requirements
- name: Create el_tracker venv and install requirements
  ansible.builtin.file:
    path: "{{ user_dir }}/{{ item }}"
    state: directory
    mode: '0755'
    owner: "{{ syno_user }}"
    recurse: yes
  loop:
    - el_tracker
    - logs

- name: Set directory owner permission
  ansible.builtin.file:
    path: "{{ user_dir }}/{{ item }}"
    state: directory
    mode: '0700'
    owner: "{{ syno_user }}"
  loop:
    - .gnupg
    - .kube
    - .ssh

- name: Setup permission for ssh
  ansible.builtin.shell: |
    chmod 600 {{ user_dir }}/.ssh/id_*
    chmod 644 {{ user_dir }}/.ssh/*pub
  become: true
  become_user: "{{ syno_user }}"
  register: ssh_perm
  until: ssh_perm.rc == 0

# configure ssh server
- name: Copy sshd_config template
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    mode: '0600'
    validate: /usr/sbin/sshd -t -f %s
    backup: yes
  register: sshd_config
  notify: Restart sshd

# Display sshd config
- name: Display sshd config result standard output lines
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop: "{{ sshd_config.stdout_lines }}"
  when: sshd_config.stdout_lines is defined

# Copy scripts
- name: Copy scripts
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0755'
    owner: "{{ syno_user }}"
  loop:
    - { src: 'autodir.py', dest: '{{ user_dir }}/autodir.py' }
    - { src: 'enable_vault_secrets', dest: '{{ user_dir }}/enable_vault_secrets' }
    - { src: 'goldfish_prep', dest: '{{ user_dir }}/goldfish_prep' }
    - { src: 'unseal_vault', dest: '{{ user_dir }}/unseal_vault' }

# Copy requirements script
- name: Copy requirements script
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0644'
    owner: "{{ syno_user }}"
  loop:
    - { src: 'bashrc', dest: '{{ user_dir }}/.bashrc' }
    - { src: 'bash_profile', dest: '{{ user_dir }}/.bash_profile' }
    - { src: 'ca.pem', dest: '{{ user_dir }}/ca.pem' }
    - { src: 'cert.pem', dest: '{{ user_dir }}/cert.pem' }
    - { src: 'key.pem', dest: '{{ user_dir }}/key.pem' }
    - { src: 'My_BSIT_Degree.jpg', dest: '{{ user_dir}}/My_BSIT_Degree.jpg' }
    - { src: 'requirements.txt', dest: '{{ user_dir }}/el_tracker/requirements.txt' }

- name: Setup pyvenv for user
  ansible.builtin.shell: |
    cd {{ user_dir }}/el_tracker
    /usr/local/bin/python3.9 -m venv elvenv
    source elvenv/bin/activate
    pip install --upgrade pip setuptools
    pip install -r requirements.txt
  become: true
  become_user: "{{ syno_user }}"
  register: pyvenv_install
  until: pyvenv_install.rc == 0

# Display pyvenv output
- name: Display pyvenv result standard output lines
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop: "{{ pyvenv_install.stdout_lines }}"
  when: pyvenv_install.stdout_lines is defined