---
services:
  registry:
    image: registry:latest
    container_name: registry
    restart: always
    ports:
      - "5000:5000"
    environment:
      #REGISTRY_AUTH: htpasswd
      #REGISTRY_AUTH_HTPASSWD_REALM: Registry-Realm
      #REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.passwd
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
      REGISTRY_STORAGE_DELETE_ENABLED: true
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin: '[http://registry.superasian.net]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods: '[HEAD,GET,OPTIONS,DELETE]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Credentials: '[true]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers: '[Authorization,Accept,Cache-Control]'
      REGISTRY_HTTP_HEADERS_Access-Control-Expose-Headers: '[Docker-Content-Digest]'
      
    volumes:
      - /AppData/registry:/var/lib/registry
      - /AppData/registry/data:/data
      - /AppData/registry/auth:/auth
    networks:
      - regnet
  registry-ui:
    image: joxit/docker-registry-ui:latest
    restart: always
    ports:
      - 8080:80
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=Docker Registry UI
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - NGINX_PROXY_PASS_URL=http://registry:5000
      - SHOW_CATALOG_NB_TAGS=true
      - CATALOG_MIN_BRANCHES=1
      - CATALOG_MAX_BRANCHES=1
      - TAGLIST_PAGE_SIZE=100
      - REGISTRY_SECURED=false
      - CATALOG_ELEMENTS_LIMIT=1000
    container_name: registry-ui
    depends_on:
      - registry
    volumes:
      - /AppData/docker-registry-ui:/opt/docker-registry-ui
    networks:
      - regnet
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /AppData/nginx/conf.d/:/etc/nginx/conf.d/
      - /AppData/nginx/ssl/:/etc/nginx/ssl/
    networks:
      - regnet

networks:
  regnet:
    driver: bridge
volumes:
  data:
    driver: local