#!/bin/bash
# cloudflare-secret.yaml
cat <<EOF | kubectl create -f -
---
apiVersion: v1
data:
  api-token: NmpiVUc0X000SjVTVVNKTzZKX2JNTTZpVFlrQlpib3N2Zkl6NEZ4dw==
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: external-dns
EOF
kubectl create namespace external-dns
# Add the External-DNS Helm repository
helm repo add external-dns https://kubernetes-sigs.github.io/external-dns/
helm repo update

# Install External-DNS with Cloudflare configuration
helm install external-dns external-dns/external-dns \
  --namespace external-dns \
  --set provider.name=cloudflare \
  --set env[0].name=CF_API_TOKEN \
  --set env[0].valueFrom.secretKeyRef.name=cloudflare-api-token \
  --set env[0].valueFrom.secretKeyRef.key=cloudflare_api_token \
  --set policy=sync \
  --set sources[0]=service \
  --set sources[1]=ingress \
  --set txtOwnerId=k8s-external-dns \
  --set domainFilters[0]=superasian.net
