#SPDX-License-Identifier: MIT-0
---
# defaults file for roles/mailcow
app_dir: "/srv/AppData"
mailcow_dir: "{{ app_dir }}/mailcow"
domain: "superasian.net"
hostname: "mailcow.superasian.net"
admin_email: "admin@superasian.net"
