---
apiVersion: external-secrets.io/v1
kind: Application
metadata:
  name: enxternal-secrets
  namespace: external-secrets-system
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 2.8.0 # Use the latest stable version
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
