#!/bin/bash
gitlabee="docker.io/gitlab/gitlab-ee"
superasian="harbor.superasian.net/library/gitlab/gitlab-ee"
tags=("18.0.1-ee.0"
      "18.0.0-ee.0"
      "17.11.3-ee.0"
      "17.11.2-ee.0"
      "17.10.7-ee.0"
      "17.10.6-ee.0")
    for tag in ${tags[@]}; do
        docker pull $gitlabee:$tag
        docker tag $gitlabee:$tag $superasian:$tag
        docker push $superasian:$tag
        docker rmi $gitlabee:$tag
    done
exit 0;
