---

name: Portainer
services:
  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    network_mode: bridge

volumes:
  portainer_data:
    driver: local
    