#!/bin/bash
rockylinux="docker.io/rockylinux/rockylinux"
superasian="harbor.superasian.net/library/rockylinux"
tags=("9.3-minimal"
      "9-minimal"
      "9.3"
      "9"
      "8.9-minimal"
      "8-minimal"
      "8.9"
      "8")
    for tag in ${tags[@]}; do
        docker pull $rockylinux:$tag
        docker tag $rockylinux:$tag $superasian:$tag
        docker push $superasian:$tag
        docker rmi $rockylinux:$tag
    done
exit 0;
