---
- name: Populate service facts
  ansible.builtin.service_facts: {}

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Include Debian-specific tasks
  ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'

- name: Include RedHat-specific tasks
  ansible.builtin.include_tasks: rhel.yml
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'Rocky'

- name: Satisfy OS Pre-Reqs
  ansible.builtin.include_tasks: pre_reqs.yml

- name: Get RKE2 server service status
  ansible.builtin.systemd:
    name: rke2-server
  register: rke2_server
  ignore_errors: true
  #when: "'rke2_servers' in group_names"

- name: Get RKE2 agent service status
  ansible.builtin.systemd:
    name: rke2-agent
  register: rke2_agent
  ignore_errors: true
  #when: "'rke2_workers' in group_names"

- name: Print RKE2 service state
  ansible.builtin.debug:
    msg: >
      Node {{ inventory_hostname }} service state is
      {{ rke2_server_status.status.ActiveState | default(rke2_agent_status.status.ActiveState) }}

- name: Include rke2-extras
  ansible.builtin.include_role:
    name: common
    tasks_from: rke2-extras
  when: 
    - rke2_server.status.ActiveState == 'running'
    - rke2_agent.status.ActiveState == 'running'