---
- name: Populate service facts
  ansible.builtin.service_facts: {}

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Include Debian-specific tasks
  ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'

- name: Include RedHat-specific tasks
  ansible.builtin.include_tasks: rhel.yml
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'Rocky'

- name: Satisfy OS Pre-Reqs
  ansible.builtin.include_tasks: pre_reqs.yml

- name: Check if nginx container is running
  ansible.builtin.shell: |
    systemctl status rke2-server.service
    systemctl status rke2-agent.service
  register: rke2_services

- name: Include rke2-extras
  ansible.builtin.include_role:
    name: common
    tasks_from: rke2-extras
  when: rke2_services.state == 'running'