---
# Create Apps Directory
- name: Create apps directory
  ansible.builtin.file:
    path: "{{ app_dir }}/{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ app_user }}"
  loop:
    - common

# Copy common stack config
- name: Copy common stack config
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
    owner: "{{ app_user }}"
  loop:
    - { src: 'files/node-exporter.yml', dest: '{{ common_dir }}/node-exporter.yml'}
    - { src: 'files/portainer-stack.yml', dest: '{{ common_dir }}/portainer-stack.yml'}
    - { src: 'files/rl8-ks.cfg', dest: '{{ common_dir }}/rl8-ks.cfg'}

# Start Common Stack
- name: Start common stack
  ansible.builtin.command:
    chdir: "{{ common_dir }}"
    cmd: "docker compose -f portainer-stack.yml up -d"
  register: compose_result
  until: compose_result.rc == 0
  retries: 5
  delay: 10

# Display compose output
- name: Display compose result standard output lines
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop: "{{ compose_result.stdout_lines }}"
  when: compose_result.stdout_lines is defined

# Copy docker config
- name: Copy daemon.json
  ansible.builtin.template:
    src: "daemon.json.j2"
    dest: "/etc/docker/daemon.json"
  notify: Restart docker

# generate containerd default config
- name: Generate containerd default config
  ansible.builtin.shell:
    cmd: |
      containerd config default | sudo tee /etc/containerd/config.toml

# Install crictl
- name: Install crictl
  ansible.builtin.unarchive:
    src: "https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.36.0/crictl-v1.36.0-linux-amd64.tar.gz"  # Path to the archive on the Ansible control machine
    dest: /usr/local/bin           # Absolute path on the remote host where the archive will be extracted
    remote_src: true                     # Set to 'yes' if the archive is already on the remote host
    owner: root            # (Optional) User to own the extracted files
    mode: '0755'                       # (Optional) Permissions for the extracted files
    #extra_opts: ['--strip-components=1'] # (Optional) Pass extra options to the unarchive command (e.g., to strip directories)

# Copy crictl config
- name: Copy crictl config
  ansible.builtin.template:
    src: "crictl.yaml.j2"
    dest: "/etc/crictl.yaml"
    mode: 0644
    owner: root
  notify: Restart containerd
