---
# Create Apps Directory
- name: Create apps directory
  ansible.builtin.file:
    path: "{{ app_dir }}/{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ app_user }}"
  loop:
    - common

# Copy common stack config
- name: Copy common stack config
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
    owner: "{{ app_user }}"
  loop:
    - { src: 'files/node-exporter.yml', dest: '{{ common_dir }}/node-exporter.yml'}
    - { src: 'files/portainer-stack.yml', dest: '{{ common_dir }}/portainer-stack.yml'}
    - { src: 'files/rl8-ks.cfg', dest: '{{ common_dir }}/rl8-ks.cfg'}

# Start Common Stack
- name: Start common stack
  ansible.builtin.command:
    chdir: "{{ common_dir }}"
    cmd: "docker compose -f portainer-stack.yml up -d"
  register: compose_result
  until: compose_result.rc == 0
  retries: 5
  delay: 10

# Display compose output
- name: Display compose result standard output lines
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop: "{{ compose_result.stdout_lines }}"
  when: compose_result.stdout_lines is defined

# Copy docker config
- name: Copy daemon.json
  ansible.builtin.template:
    src: "daemon.json.j2"
    dest: "/etc/docker/daemon.json"
  notify: Restart docker

# Fix containerd runtime config
- name: Fix containerd runtime config
  ansible.builtin.shell:
    cmd: |
      containerd config default | sudo tee /etc/containerd/config.toml
      #sed -i 's|^state = ".*"|state = "/var/run/containerd"|' /etc/containerd/config.toml
      #sed -i '/^\[grpc\]$/,/^\[/ s|^ address = ".*"| address = "/var/run/containerd/containerd.sock"|' /etc/containerd/config.toml

# Copy crictl config
- name: Copy crictl.yaml
  ansible.builtin.template:
    src: "crictl.yml.j2"
    dest: "/etc/crictl.yml"
  notify: Restart containerd