---
# Create Apps Directory
- name: Create apps directory
  ansible.builtin.file:
    path: "{{ app_dir }}/{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ app_user }}"
  loop:
    - common

# Copy common stack config
- name: Copy common stack config
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
    owner: "{{ app_user }}"
  loop:
    - { src: 'files/node-exporter.yml', dest: '{{ common_dir }}/node-exporter.yml'}
    - { src: 'files/portainer-stack.yml', dest: '{{ common_dir }}/portainer-stack.yml'}
    - { src: 'files/rl8-ks.cfg', dest: '{{ common_dir }}/rl8-ks.cfg'}

# Start Common Stack
- name: Start common stack
  ansible.builtin.command:
    chdir: "{{ common_dir }}"
    cmd: "docker compose -f portainer-stack.yml up -d"
  register: compose_result
  until: compose_result.rc == 0
  retries: 5
  delay: 10

# Display compose output
- name: Display compose result standard output lines
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop: "{{ compose_result.stdout_lines }}"
  when: compose_result.stdout_lines is defined

# Copy docker config
- name: Copy daemon.json
  ansible.builtin.template:
    src: "daemon.json.j2"
    dest: "/etc/docker/daemon.json"
  notify: Restart docker

- name: Check if rke2 is running
  ansible.builtin.shell: |
    systemctl status rke2-server.service
    systemctl status rke2-agent.service
  register: rke2_services
  ignore_errors: true

# Display rke2 services
- name: Display rke2 services result standard output lines
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop: "{{ rke2_services.stdout_lines }}"
  when: rke2_services.stdout_lines is defined

# generate containerd default config
- name: Generate containerd default config
  ansible.builtin.shell:
    cmd: |
      containerd config default | sudo tee /etc/containerd/config.toml
  when: rke2_services.stdout != 'running'

# Add public keys to authorized_keys
- name: Set up multiple authorized keys
  ansible.posix.authorized_key:
    user: "{{ app_user }}"
    state: present
    key: "{{ lookup('file', item) }}"
    loop:
      - id_ed25519.pub
      - id_rsa.pub
  register: ssh_pub_keys

# Display ssh public keys
- name: Display ssh pub keys result standard output lines
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop: "{{ ssh_pub_keys.stdout_lines }}"
  when: ssh_pub_keys.stdout_lines is defined