---
services:
  artifactory:
    image: releases-docker.jfrog.io/jfrog/artifactory-oss:latest
    container_name: artifactory-oss
    volumes:
      - /srv/dev-disk-by-uuid-b5f61a9b-1827-498b-a77b-7caf811c025b/DATA/ARCHIVE/artifactory_data:/var/opt/jfrog/artifactory
      - /etc/localtime:/etc/localtime:ro
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    network_mode: bridge
    ports:
      - 8082:8082 # for router communication
      - 8081:8081 # for artifactory communication
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
    environment:
      - ENABLE_MIGRATION=y
      - JF_SHARED_DATABASE_TYPE=postgresql
      # The following must match the POSTGRES_USER and POSTGRES_PASSWORD values passed to PostgreSQL
      - JF_SHARED_DATABASE_USERNAME=artifactory
      - JF_SHARED_DATABASE_PASSWORD=mIb9nPKQ8LnaSHMWV1cG3A==
      - JF_SHARED_DATABASE_URL=jdbc:postgresql://10.0.0.252:5432/artifactory
      - JF_SHARED_DATABASE_DRIVER=org.postgresql.Driver
      - JF_SHARED_NODE_IP=10.0.0.16
      - JF_SHARED_NODE_ID=artifactory
      - JF_SHARED_NODE_NAME=artifactory
      - JF_ROUTER_ENTRYPOINTS_EXTERNALPORT=8082
