---
- name: Install packages
  hosts: all
  tasks:
  - name: Install Debian packages
    shell: |
      apt-get update && apt-get install -y python-is-python3 python3-pip python3-setuptools python3-smbus \
      libi2c-dev fancontrol read-edid i2c-tools lm-sensors strace htop bmon firmware-amd-graphics \
      firmware-iwlwifi firmware-realtek firmware-misc-nonfree
    become: true
    become_user: root
    become_method: sudo
    when: ansible_facts['os_family'] == "Debian" or ansible_facts['os_family'] == "Ubuntu"

  - name: Install Redhat packages
    shell: |
      dnf install -y python39 python3-pip python3-setuptools nfs-utils net-tools
    become: true
    become_user: root
    become_method: sudo
    when: ansible_facts['os_family'] == "RedHat" or ansible_facts['os_family'] == "Rocky"

  - name: Install windows packages
    win_chocolatey:
      name: '{{ item }}'
      state: present
    loop:
    - 7zip
    - awscli
    - git
    - golang
    - nodejs-lts
    - notepadplusplus
    - python3
    - ruby
    - VisualStudioCode
    become: true
    #become_user: Administrator
    become_method: runas
    when: ansible_facts['os_family'] == "Windows"
