- name: Install kube-vip
  hosts: infra01
  become: true
  vars:
    - WATCHDIR: "/var/lib/rancher/rke2/server/manifests"
    - CONFDIR: "/etc/rancher/rke2"
    - CONFFILE: "{{ CONFDIR }}/config.yaml"
    - SERVER_FAILOVER_IP: "192.168.0.202"
    - INTERFACE: "enp3s0"
    - VIP: "{{ SERVER_FAILOVER_IP }}"
    - KUBE_VIP_IMAGE: "docker.io/plndr/kube-vip"
    - KUBE_VIP_IMAGE_TAG: "latest"

  tasks:
  - name: Download kube-vip RBAC file
    get_url:
      url: https://kube-vip.io/manifests/rbac.yaml
      dest: "{{ WATCHDIR }}/kube-vip-rbac.yaml"
      owner: root
      group: root
      mode: 0644

  - name: Deploying kube-vip
    shell: |
      ctr --namespace k8s.io image pull "{{ KUBE_VIP_IMAGE }}":"{{ KUBE_VIP_IMAGE_TAG }}"
      ctr --namespace k8s.io run --rm --net-host "{{ KUBE_VIP_IMAGE }}":"{{ KUBE_VIP_IMAGE_TAG }}" vip /kube-vip \
      manifest daemonset \
      --arp \
      --interface "{{ INTERFACE }}" \
      --address "{{ VIP }}" \
      --controlplane \
      --leaderElection \
      --taint \
      --services \
      --inCluster | tee "{{ WATCHDIR }}/kube-vip.yaml"
