---
# Reset Mailcow server
- name: Reset Mailcow server
  hosts: all
  any_errors_fatal: true
  become: true
  become_user: root
  tasks:
    - name: Reset mailcow
      ansible.builtin.shell: |
        cd /srv/AppData/mailcow
        docker compose down -v --rmi all --remove-orphans
        rm -rf /srv/AppData/mailcow
      register: reset_mailcow_result
      until: reset_mailcow_result.rc == 0
      retries: 3
      delay: 30