---
# Reset Synology DSM
- name: Reset Synology DSM
  hosts: all
  any_errors_fatal: true
  become: true
  become_user: root
  vars:
    syno_packages:
      - ContainerManager
      - DhcpServer
      - DNSServer
      - LogCenter
      - NoteStation
      - Perl
      - WebStation
      - TextEditor
  tasks:
    - name: Get list of installed packages
      when: true
      changed_when: false
      ansible.builtin.command: /usr/syno/bin/synopkg list --name
      register: synopkg_list

    - name: Remove all installed packages
      ansible.builtin.command: /usr/syno/bin/synopkg uninstall {{ package }}
      loop: "{{ syno_packages }}"
      loop_control:
        loop_var: package
      when: package in synopkg_list.stdout_lines

    - name: Remove shares
      ansible.builtin.command: |
        /usr/syno/bin/synoshare --del {{ item }} TRUE
      loop:
        - /volume1/apps
        - /volume1/docker
      ignore_errors: true

    - name: Remove PXE folder and contents
      ansible.builtin.shell: rm -rf /var/services/homes/k0ng/{{ item }}
      loop:
        - .bash_profile
        - .bashrc
        - el_tracker
        - enable_vault_secrets
        - goldfish_prep
        - change_default_ports
        - My_BSIT_Degree.jpg
        - pysetup
        - restore_default_ports
      ignore_errors: true
