---
# Reset Synology DSM
- name: Reset Synology DSM
  hosts: all
  any_errors_fatal: true
  become: true
  become_user: root
  vars:
    syno_packages:
        - ContainerManager
        - DhcpServer
        - DNSServer
        - LogCenter
        - Node.js_v20
        - NoteStation
        - Perl
        - Apache2.4
        - WebStation
        - TextEditor
        - StorageManager
        - PHP8.4
        - LogCenter

  tasks:
    - name: Get list of installed packages
      when: true
      changed_when: false
      ansible.builtin.command: /usr/syno/bin/synopkg list --name
      register: synopkg_list

    - name: Remove all installed packages
      ansible.builtin.command: /usr/syno/bin/synopkg uninstall {{ package }}
      loop: "{{ syno_packages }}"
      loop_control:
        loop_var: package
      when: package in synopkg_list.stdout_lines

    - name: Remove extras
      ansible.builtin.shell: |
        rm -rf /usr/local/go/
        rm -f /usr/local/bin/{{ item }}
      loop:
        - kubectl
        - vault
        - helm
        - docker-credential-vault-login

    - name: Remove PXE folder and contents
      ansible.builtin.shell: rm -rf /var/services/homes/k0ng/{{ item }}
      loop:
        - .bash_profile
        - .bashrc
        - el_tracker
        - enable_vault_secrets
        - goldfish_prep
        - My_BSIT_Degree.jpg
        - pysetup
      ignore_errors: true
      become_user: k0ng
