---

- name: Tear Down rke2 cluster
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Reset rke2 cluster
      shell: |
        rke2-killall.sh
        rke2-uninstall.sh
        systemctl restart containerd
