---
- hosts: all
  vars:
    scan_use_checksum: false
    scan_use_recursive: false
  tasks:

    - name: "Scan packages (Unix/Linux)"
      scan_packages:
        os_family: '{{ ansible_os_family }}'
      when: ansible_os_family != "Windows"
    - name: "Scan services (Unix/Linux)"
      scan_services:
      when: ansible_os_family != "Windows"
    - name: "Scan files (Unix/Linux)"
      scan_files:
        paths: '{{ scan_file_paths }}'
        get_checksum: '{{ scan_use_checksum }}'
        recursive: '{{ scan_use_recursive }}'
      when: scan_file_paths is defined and ansible_os_family != "Windows"
    - name: "Scan Insights for Machine ID (Unix/Linux)"
      scan_insights:
      when: ansible_os_family != "Windows"

    - name: set the default shell to PowerShell
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\OpenSSH
        name: DefaultShell
        data: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
        type: string
        state: present
      when: ansible_os_family == "Windows"

    - name: reset SSH connection after shell change
      ansible.builtin.meta: reset_connection
      when: ansible_os_family == "Windows"

    # - name: set the default shell to cmd
    #   ansible.windows.win_regedit:
    #     path: HKLM:\SOFTWARE\OpenSSH
    #     name: DefaultShell
    #     state: absent

    # - name: reset SSH connection after shell change
    #   ansible.builtin.meta: reset_connection

    - name: "Scan packages (Windows)"
      win_scan_packages:
      when: ansible_os_family == "Windows"
    - name: "Scan services (Windows)"
      win_scan_services:
      when: ansible_os_family == "Windows"
    - name: "Scan files (Windows)"
      win_scan_files:
        paths: '{{ scan_file_paths }}'
        get_checksum: '{{ scan_use_checksum }}'
        recursive: '{{ scan_use_recursive }}'
      when: scan_file_paths is defined and ansible_os_family == "Windows"
