---
- name: Install Softwares
  hosts: all
  become: true
  become_user: Administrator
  become_method: runas
  tasks:
    # This assumed chocolatey is already installed. If not then install chocolatey first
    - name: Install softwares using chocolatey
      win_chocolatey:
        name: "{{ item }}"
        state: present
        force: true
      loop:
        - awscli
        - dotnet-desktopruntime
        - dotnet-runtime
        - dotnet-sdk
        - git
        - golang
        - keepassxc
        - nodejs-lts
        - python313
        - ruby
        - vscode

