---
- name: Install Software
  hosts: all
  become: true
  become_user: Administrator
  become_method: runas
  tasks:

    - name: Uninstall packages using chocolatey
      win_chocolatey:
        name:
          - 7zip
          - awscli
          - dotnet-9.0-runtime
          - git
          - golang
          - nodejs-lts
          - notepadplusplus
          - python313
          - ruby
          - vscode
        state: absent
        force: true

    - name: Uninstall using powershell
      win_shell: |

        # Remove aws modules
        awsmodules = @(
          'AWS.Tools.AutoScaling'
          'AWS.Tools.CloudFormation'
          'AWS.Tools.CloudWatchLogs'
          'AWS.Tools.Common'
          'AWS.Tools.EC2'
          'AWS.Tools.Elasticsearch'
          'AWS.Tools.IdentityManagement'
          'AWS.Tools.Lambda'
          'AWS.Tools.RDS'
          'AWS.Tools.Route53'
          'AWS.Tools.S3'
          'AWS.Tools.SecretsManager'
          'AWS.Tools.SecurityToken'
          'AWSLambdaPSCore'
          'AWSPowershell.NetCore'
        )
        foreach ($mod in $awsmodules)
        {
          Uninstall-Module -ModuleInfo $mod -Force
        }
