---
- name: Install Softwares
  hosts: all
  become: true
  become_user: Administrator
  become_method: runas
  tasks:
    # Make sure chocolatey is installed before installing softwares
    - name: Ensure Chocolatey itself is installed, using a specific bootstrap script and target nupkg
      win_chocolatey:
        name: chocolatey
        bootstrap_script: https://www.superasian.net/repo/chocolateyInstall.ps1
      environment:
        chocolateyDownloadUrl: "https://www.superasian.net/repo/chocolatey.1.1.0.nupkg"

    - name: Ensure .NET Framework 4.8 requirement is satisfied for Chocolatey CLI v2.0.0+
      block:
      - name: install Chocolatey CLI v1.4.0
        win_chocolatey:
          name: 'chocolatey'
          state: present
          version: '1.4.0'

      - name: install Microsoft .NET Framework 4.8
        win_chocolatey:
          name: 'netfx-4.8'
          state: present

      - name: Reboot the host to complete .NET Framework 4.8 install
        ansible.windows.win_reboot:
          reboot_timeout: 600

      - name: Install Chocolatey CLI v2.0.0+ when .NET Framework 4.8 dependency is met
        win_chocolatey:
          name: 'chocolatey'
          state: latest

    - name: Install softwares using chocolatey
      win_chocolatey:
        name: "{{ item }}"
        state: present
        force: true
      loop:
        - 7zip
        - awscli
        - dotnet-9.0-runtime
        - git
        - golang
        - nodejs-lts
        - notepadplusplus
        - python313
        - ruby
        - vscode

    # - name: Install using powershell
    #   win_shell: |
    #     # Add Python & Ruby to PATH
    #     Set-Item -Path Env:Path -Value ($Env:Path + "C:\Python313;C:\Python313\Scripts;C:\tools\ruby34\bin")
    #     # Install AWS Modules
    #     awsmodules = @(
    #       - AWS.Tools.AutoScaling'
    #       - AWS.Tools.CloudFormation'
    #       - AWS.Tools.CloudWatchLogs'
    #       - AWS.Tools.Common'
    #       - AWS.Tools.EC2'
    #       - AWS.Tools.Elasticsearch'
    #       - AWS.Tools.IdentityManagement'
    #       - AWS.Tools.Lambda'
    #       - AWS.Tools.RDS'
    #       - AWS.Tools.Route53'
    #       - AWS.Tools.S3'
    #       - AWS.Tools.SecretsManager'
    #       - AWS.Tools.SecurityToken'
    #       - AWSLambdaPSCore'
    #       - AWSPowershell.NetCore'
    #     )
    #     foreach ($mod in $awsmodules)
    #     {
    #       Install-Module -Name $mod -AllowClobber -Force
    #     }