---
- name: Install Software
  hosts: all
  become: true
  become_user: Administrator
  become_method: runas
  tasks:

    - name: Set the default shell to PowerShell
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\OpenSSH
        name: DefaultShell
        data: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
        type: string
        state: present

    - name: Reset SSH connection after shell change
      ansible.builtin.meta: reset_connection

    - name: Uninstall using powershell
      win_shell: |
        # Uninstall apps
        $appArray = @(
            '7zip'
            '7zip.install'
            'awscli'
            'dotnet-9.0-runtime'
            'git'
            'git.install'
            'golang'
            'nodejs-lts'
            'notepadplusplus'
            'notepadplusplus.install'
            'ruby'
            'ruby.install'
            'vscode'
            'vscode.install'
        )
        foreach ($app in $appArray) {
          choco uninstall -y $app --force
        }
        # Remove aws modules
        $awsmodules = @(
          'AWS.Tools.AutoScaling'
          'AWS.Tools.CloudFormation'
          'AWS.Tools.CloudWatchLogs'
          'AWS.Tools.Common'
          'AWS.Tools.EC2'
          'AWS.Tools.Elasticsearch'
          'AWS.Tools.IdentityManagement'
          'AWS.Tools.Lambda'
          'AWS.Tools.RDS'
          'AWS.Tools.Route53'
          'AWS.Tools.S3'
          'AWS.Tools.SecretsManager'
          'AWS.Tools.SecurityToken'
          'AWSLambdaPSCore'
          'AWSPowershell.NetCore'
        )
        foreach ($mod in $awsmodules) {
          Uninstall-Module -ModuleInfo $mod -Force
        }
