---
- name: Uninstall Software
  hosts: all
  become: true
  become_user: Administrator
  become_method: runas
  tasks:
    # This assumed chocolatey is already installed. If not then install chocolatey first
    - name: Uninstall softwares using chocolatey
      win_chocolatey:
        name: "{{ item }}"
        state: absent
        force: true
      loop:
        - 7zip
        - 7zip.install
        - awscli
        - dotnet-9.0-runtime
        - git
        - git.install
        - golang
        - nodejs-lts
        - notepadplusplus
        - notepadplusplus.install
        - python313
        - ruby
        - vscode
