---
- name: Install Packages
  hosts: all
  become: true
  become_user: Administrator
  become_method: runas
  tasks:

    - name: Set the default shell to PowerShell
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\OpenSSH
        name: DefaultShell
        data: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
        type: string
        state: present

    - name: Reset SSH connection after shell change
      ansible.builtin.meta: reset_connection

    - name: Uninstall using powershell
      win_shell: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
        choco upgrade -y chocolatey
        $appArray = @(
            '7zip'
            'awscli'
            'golang'
            'git'
            'nodejs-lts'
            'notepadplusplus'
            'python313'
            'ruby'
            'vscode'
        )
        foreach ($app in $appArray) {
          choco uninstall -y $app
        } 
        Remove-Item -Path Env:Path -Value ($Env:Path + "C:\Python313;C:\tools\ruby34\bin")
