---
# Create Nginx Directory
- name: Create nginx directory
  ansible.builtin.file:
    path: "{{ app_dir }}/nginx/{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ app_user }}"
  loop:
    - conf.d
    - ssl

# Copy certs & config
- name: Copy certs
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
    owner: "{{ app_user }}"
  loop:
    - { src: 'files/tls.cert', dest: '{{ app_dir }}/nginx/ssl/tls.cert' }
    - { src: 'files/tls.key', dest: '{{ app_dir }}/nginx/ssl/tls.key' }
    - { src: 'files/artifactory.conf', dest: '{{ app_dir }}/nginx/conf.d/artifactory.conf' }
